# env:
language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - 'node_modules'
services:
  - postgresql
env:
  - CODECLIMATE_REPO_TOKEN=0f1f0fc0b250f84a120207bbcea65ce3b06f78000f3a3f02e250e42d5a83f2c5
# before_install: cd api
install:
  - npm install
before_script:
  - cat .env.travis >> .env
  - psql -c "DROP DATABASE travis;" -U postgres
  - psql -c "CREATE DATABASE travis;" -U postgres
  - psql -c "CREATE USER root WITH PASSWORD 'password';" -U postgres
script:
  - npm run test
after_success:
  - npm run coverage
